### ISSUE TITLE
Complete data.xlsx

### ISSUE THREAD

**Issue by patrickwalls** [UBCMath/coursemap#1]
The spreadsheet data.xlsx contains course information but it is incomplete.

Fill in necessary data by copying and pasting from the [UBC Course Calendar](http://www.calendar.ubc.ca/vancouver/courses.cfm?page=code&code=MATH).

**Comment by LeoLee5566** [comment]
I just made the push but forgot to checkout to my own branch (for the second time, still not very familiar with git). At least the excel file in the main branch is the most recent now. 
In 'requisite' sheet, I use 'pre_soft' tag to clarify the case that a student can choose either of the soft prerequisite condition to meet the requirement. (Useless for now)
(e.g. To take Math 121, a student must have either (a) a score of 68% or higher in MATH 120 or (b) a score of 80% or higher in one of MATH 100, MATH 102, MATH 104, MATH 180, MATH   184 or (c) a score of 5 in AP Calculus AB. Thus both 120 and [100,102,104,180,184] are marked as soft-prerequisite).



--


)

**Comment by patrickwalls** [comment]
Okay. Sounds good. We modify the soft prerequisites later if needed.
