### ISSUE TITLE
Import multiple datasets

### ISSUE THREAD

**Issue by patrickwalls** [UBCMath/coursemap#15]
We are using d3.csv to import datasets but we are nesting d3.csv for each one. There will be more datasets to load. There should be a better way to load the data instead of nested functions.

**Comment by LeoLee5566** [comment]
We can simply use Promise.all. Fixed.
<img width="679" alt="WX20210212-170412@2x" src="https://user-images.githubusercontent.com/40313248/107748711-7276c980-6d54-11eb-9e4d-3dbd063c78e7.png">

**Comment by patrickwalls** [comment]
Resolved in #20.
