### ISSUE TITLE
Display course information on hover

### ISSUE THREAD

**Issue by patrickwalls** [UBCMath/coursemap#3]
The map should display course name, prerequisites and other information when the user hovers the cursor over a node. See the following [example](https://bl.ocks.org/d3noob/a22c42db65eb00d4e369) of tooltips in d3.

**Comment by patrickwalls** [comment]
The prerequisites (and corequisites) lines should also change color with hover.

**Comment by LeoLee5566** [comment]
working on it

**Comment by LeoLee5566** [comment]
Demo here: https://codepen.io/leolee5566-the-vuer/pen/PoGvKpz?editors=0111. I prefer working with codepen. If you are happy with this demo, I'll do the github things then.

**Comment by patrickwalls** [comment]
It looks pretty good. I would like the course numbers to be centered at the nodes and inside the circles. The course info should display the course number as well. And the text is should be displayed more neatly. Right now it displays on several lines.

**Comment by patrickwalls** [comment]
Create a new branch and push to the repo. I would like to try your work.

**Comment by patrickwalls** [comment]
The text should also include the course title and prerequisite text.

**Comment by patrickwalls** [comment]
Resolved in #22.
