### ISSUE TITLE
Enable GitHub pages

### ISSUE THREAD

**Issue by patrickwalls** [UBCMath/coursemap#6]
Setup GitHub pages so that people can view the course map at ubcmath.github.io/coursemap.

**Comment by zzzzzyzzzzz** [comment]
I'm working on this task

**Comment by zzzzzyzzzzz** [comment]
Hello Patrick, I have folk the repo to my account because I don't have the authority to modify the setting of the repo. I have set the webpage in the repo that I forked from here successfully, and the domain name is https://kkkarenzhou.github.io/coursemap/ .

**Comment by patrickwalls** [comment]
Okay. I enabled GitHub pages on our repo. I thought there was more to it but it was trivial.
